### ISSUE TITLE
Feature Complete checklist

### ISSUE THREAD

**Issue by sebirdman** [diefarbe/node-lib#1]
What do we need to do for the lib to be "feature complete"?

Here's a list I've got

- [ ] Cross Compatible (windows/linux/osx)
- [ ] Can change colors of individual keys
- [ ] Can make individual keys blink
- [ ] Can switch profiles
- [ ] Can create profiles?

**Comment by mikejr83** [comment]
This being a library I just want to make sure we have clarity on the profile stuff:

If profiles are stored somewhere in the keyboard firmware then it would make sense for the lib to read/write/activate them. However if they're more of a software defined thing then we should approach the library from the aspect of creating a structure for defining a profile and submitting it to the keyboard.

I'm thinking from our discussions so far that profiles are more of a software definition than what is stored in the keyboard itself (I'd like to be proven wrong here because it would be hella nice to store it and not worry about loosing state). Approaching the issue from that angle I think the library should define what is a profile and then facilitate publishing the changes to the keys.

**Comment by mikejr83** [comment]
FYI I'm going to break each one of those points out above into a "feature request"

**Comment by sebirdman** [comment]
yes, 100% on the profile stuff. It seems like it's entirely software based. Didn't know this at that time. I'll remove it. 

AFAIK - we have cross platform support for linux and mac, has anyone tested windows?

With this PR: https://github.com/diefarbe/node-lib/pull/5 we've basically got full control over the packet.
